theme: jekyll-theme-minimal
title: Portafolio
description: I hold a Ph.D. in Phycics from CINVESTAV, with experience in the field of nanomaterials; in the optical and structural characterization of materials; in Python programming and Data Science. Knowledge in Pandas, Numpy, Matplotlib, Sklearn, machine learning and SQL.
